### ISSUE TITLE
Error with samtools flagstat

### ISSUE THREAD

**Issue by nmousavi** [googlegenomics/htsget#33]
Cmd:

samtools flagstat http://localhost:1234/reads/deepvariant/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam

Error:
[W::sam_read1] parse error at line 1
[bam_flagstat_core] Truncated file? Continue anyway.

Log/msg:
[W::sam_read1] parse error at line 1
[bam_flagstat_core] Truncated file? Continue anyway.
0 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 mapped (N/A : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

It should have return this:
52035 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
297 + 0 duplicates
51873 + 0 mapped (99.69% : N/A)
52035 + 0 paired in sequencing
26006 + 0 read1
26029 + 0 read2
51574 + 0 properly paired (99.11% : N/A)
51711 + 0 with itself and mate mapped
162 + 0 singletons (0.31% : N/A)
30 + 0 with mate mapped to a different chr
26 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by kemp-google** [comment]
- What version of samtools and htslib are you using?
- Please show how you launched the htsget server

**Comment by kemp-google** [comment]
Closing; please re-open if you can reproduce.
