### ISSUE TITLE
htsget conformance test fails with non-matching reads for some files

### ISSUE THREAD

**Issue by kemp-google** [googlegenomics/htsget#35]
It has been reported that the htsget server fails the streaming test for the NA12891.bam and NA12892.bam  inputs.

The streaming test is here:
   https://github.com/jeromekelleher/htsget-tester

Logs from a failure are here:
  https://drive.google.com/file/d/0BwPXPVZF6LV3MzAxZmRjLTZJblU/edit

**Comment by anamanolache** [comment]
Test fails because it removes the placed reads from the local results before comparing them with the remote results. Htsget protocol specs are ambiguous about whether placed unmapped reads should be returned when region is specified.

**Comment by anamanolache** [comment]
The problem was fiexed in [this PR](https://github.com/jeromekelleher/htsget-tester/pull/19) by removing the --filter-unmapped flasg from the google tests
